title: adit modhvadia
url: "https://aditmodhvadia.github.io"
baseurl: "https://aditmodhvadia.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: "G-JSJ2D9LW0W"

footer: yes
footer_url: "https://aditmodhvadia.github.io"
footer_text: "adit modhvadia<br><br>"

sass:
  style: compressed
  sass_dir: _sass

nav:
# - name: "About"
#   link: "/"
#  - name: "portfolio"
#  link: "/portfolio/"
#  - name: "google scholar"
#  link: "https://scholar.google.com/citations?user=pbuqtFQAAAAJ"
#  - name: "blog"
#  link: "https://medium.com/@amanag.11"
#  - name: "CV"
#    link: "/files/cv12sep.pdf"

