title: Aman Agarwal
url: "https://amanagarwal.io"
baseurl: "https://amanagarwal.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://amanagarwal.io"
footer_text: "Aman Agarwal<br><br>"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/"
 - name: "Portfolio"
   link: "/portfolio/"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=pbuqtFQAAAAJ"
 - name: "Blog"
   link: "https://medium.com/@amanag.11"
#  - name: "CV"
#    link: "/files/cv12sep.pdf"

